Sparse matrix , scipy

In [1]:
import numpy as np
import pandas as pd

ratings = {
  'user_id': [1, 2, 4],
  'movie_id': [2, 3, 7],
  'rating': [4, 3, 1]
}
ratings = pd.DataFrame(ratings)

In [2]:
ratings

user_id  movie_id  rating
0        1         2       4
1        2         3       3
2        4         7       1

In [9]:
# Pandas pivot을 이용해서 full matrix로 변환하는 경우
rating_matrix = ratings.pivot(index='user_id', columns='movie_id',values='rating').fillna(0)
full_matrix1 = np.array(rating_matrix)
print(rating_matrix)
print(full_matrix1)

movie_id    2    3    7
user_id                
1         4.0  0.0  0.0
2         0.0  3.0  0.0
4         0.0  0.0  1.0
[[4. 0. 0.]
 [0. 3. 0.]
 [0. 0. 1.]]


In [8]:
# Sparse matrix를 이용해서 full amtrix로 변환하는 경우
from scipy.sparse import csr_matrix

data = np.array(ratings['rating'])
row_indices = np.array(ratings['user_id'])
col_indices = np.array(ratings['movie_id'])
rating_matrix = csr_matrix((data, (row_indices, col_indices)), dtype=int)
print(rating_matrix)
full_matrix2 = rating_matrix.toarray()
print(full_matrix2)

  (1, 2)	4
  (2, 3)	3
  (4, 7)	1
[[0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]


In [10]:
print(rating_matrix * 2)
print(rating_matrix.T)
print(rating_matrix.dot(rating_matrix.T))

movie_id    2    3    7
user_id                
1         8.0  0.0  0.0
2         0.0  6.0  0.0
4         0.0  0.0  2.0
user_id     1    2    4
movie_id               
2         4.0  0.0  0.0
3         0.0  3.0  0.0
7         0.0  0.0  1.0
user_id     1    2    4
user_id                
1        16.0  0.0  0.0
2         0.0  9.0  0.0
4         0.0  0.0  1.0


추천 알고리즘에 적용

In [13]:
import os

path = 'C:/Users/Hi/.surprise_data/'
os.listdir(path)

['ml-100k']

In [ ]:
import pandas as pd

r_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_csv(path + 'u.data', sep='\t', names=r_cols, encoding='latin-1')
ratings.drop('timestamp', axis=1, inplace=True)